# Generated by Django 3.2.20 on 2024-02-21 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del Producto')),
                ('medida', models.CharField(blank=True, max_length=255, null=True, verbose_name='Medida (por ejemplo: cm, pulg, kg, oz o litros)')),
                ('codigo_barras', models.CharField(max_length=255, verbose_name='Codigo de Barra')),
                ('codigo_producto', models.CharField(blank=True, max_length=25, null=True, unique=True, verbose_name='Codigo del Producto')),
                ('existencia', models.PositiveIntegerField(blank=True, null=True, verbose_name='Existencias Disponible')),
                ('precio_venta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio de Venta')),
                ('precio_compra', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio de Compra')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imagen del Producto')),
            ],
            options={
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
