# Generated by Django 3.2.20 on 2024-02-21 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigo_barras',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Codigo de Barra'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigo_producto',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True, verbose_name='Codigo Producto'),
        ),
    ]
