# Generated by Django 4.2 on 2024-06-03 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0002_alter_producto_existencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='existencia',
            field=models.IntegerField(default=0, verbose_name='Existencias del Producto'),
        ),
    ]
