# Generated by Django 4.2 on 2024-02-26 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0002_auto_20240221_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigo_producto',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Codigo Producto'),
        ),
    ]
