# Generated by Django 4.2 on 2024-05-17 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0004_alter_producto_precio_compra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='existencia',
            field=models.IntegerField(blank=True, null=True, verbose_name='Existencias Disponible'),
        ),
    ]
