# Generated by Django 4.2 on 2024-05-17 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0005_alter_producto_existencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='existencia',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
