# Generated by Django 4.2 on 2024-05-17 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0007_alter_producto_existencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nombre del Producto'),
        ),
    ]
