# Generated by Django 4.2 on 2024-05-17 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0007_alter_producto_existencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='existencia',
            field=models.PositiveIntegerField(default=0, max_length=255, verbose_name='Existencias'),
        ),
    ]
