# Generated by Django 4.2 on 2024-03-05 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Venta', '0002_ventamodel_total_invertido'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventamodel',
            name='ganancia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
